FROM tensorflow/tensorflow:2.20.0-gpu
WORKDIR /workspace

# Additional dependencies
COPY requirements_train.txt .
RUN python3 -m pip install --upgrade pip && \
    pip install --ignore-installed -r requirements_train.txt

CMD ["bash"]
